name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Install
      - name: Install Dependencies
        run: npm ci
      # Build
      - name: Build React App
        run: npm run build
      # Deploy
      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --exclude '.git/*' --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          SOURCE_DIR: "dist"
