name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      # Install
      - name: Install Dependencies
        run: npm ci
      # Create env
      - name: create env
        run: |
          echo "VITE_BACKEND_API_KEY=${{ secrets.BACKEND_API_KEY }}" >> .env
          echo "VITE_BACKEND_BASE_URL=${{ secrets.BACKEND_BASE_URL }}" >> .env
          echo "VITE_RRCAPTCHA_SITEKEY=${{ secrets.RRCAPTCHA_SITEKEY }}" >> .env
          echo "VITE_AMEDAS_OBSLIST_URL=${{ secrets.AMEDAS_OBSLIST_URL }}" >> .env
      # Build
      - name: Build React App
        run: npm run build
      # Deploy
      - name: Upload to S3
        if: github.ref == 'refs/heads/main'
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --exclude '.git/*' --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          SOURCE_DIR: "dist"
